# Generated by Django 4.0.4 on 2022-04-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='caption',
            new_name='patient',
        ),
    ]
